98
( @ vA . @ vB .  ( pr2_hidden(vA,vB) -> ~ pr2_hidden(vB,vA) ) )
( @ vA .  ( pv1_xboole_0(vA) -> pv1_fpraenfkel(vA) ) )
( @ vA .  ( pv1_xboole_0(vA) -> pv1_finset_1(vA) ) )
( @ vA .  ( pv1_xboole_0(vA) -> pv1_funct_1(vA) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ( pv3_prelat_1(vB) -> pv1_ppre_ciprc(vB,vA) ) ) )
( @ vA .  ( ~ pv1_xboole_0(vA) -> @ vB .  ( pm1_pboole(vB,vA) -> ( pv2_prelat_1(vB) -> ~ pv3_prelat_1(vB) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC . ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( pv2_closupre2(vC,vA,vB) -> ( pv1_fpraenfkel(vC) and pv1_closupre2(vC,vA,vB) ) ) ) ) )
( @ vA .  ( pv1_finset_1(vA) -> @ vB .  ( pm1_subset_1(vB,fk1_zfpmisc_1(vA)) -> pv1_finset_1(vB) ) ) )
( @ vA .  ( ( pv1_prelat_1(vA) and pv1_xboole_0(vA) and pv1_funct_1(vA) ) -> ( pv1_prelat_1(vA) and pv1_funct_1(vA) and pv2_funct_1(vA) ) ) )
( @ vA . @ vB .  ( ( pv1_ppre_ciprc(vB,vA) and pm1_pboole(vB,vA) ) -> @ vC .  ( pm4_pboole(vC,vA,vB) -> pv1_ppre_ciprc(vC,vA) ) ) )
( @ vA .  ( ~ pv1_xboole_0(vA) -> @ vB .  ( pm1_pboole(vB,vA) -> ( pv3_prelat_1(vB) -> ~ pv2_prelat_1(vB) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( pv4_closupre2(vC,vA,vB) -> ( pv1_fpraenfkel(vC) and pv3_closupre2(vC,vA,vB) ) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( pv4_closupre2(vC,vA,vB) -> ( pv1_fpraenfkel(vC) and pv5_closupre2(vC,vA,vB) ) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( pv5_closupre2(vC,vA,vB) -> ( ~ pv1_xboole_0(vC) and pv1_fpraenfkel(vC) ) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( pv2_closupre2(vC,vA,vB) -> ( pv1_fpraenfkel(vC) and pv6_closupre2(vC,vA,vB) ) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( pv6_closupre2(vC,vA,vB) -> ( ~ pv1_xboole_0(vC) and pv1_fpraenfkel(vC) ) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> (((pv3_prelat_1(vB)) -> (@ vvC .  ( pr2_hidden(vC,vA) -> pv1_xboole_0(fk1_funct_1(vB,vC)) ))) and ((@ vvC .  ( pr2_hidden(vC,vA) -> pv1_xboole_0(fk1_funct_1(vB,vC)) )) -> (pv3_prelat_1(vB)))) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_pboole(vC,vA) -> ((pEq(vC,fk2_pmboolean(vA,vB)) -> @ vD .  pr2_hidden(vD,vA) -> pEq(fk1_funct_1(vC,vD),fk3_taprsfki(fk1_funct_1(vB,vD)))) and ((@ vD .  ( pr2_hidden(vD,vA) -> pEq(fk1_funct_1(vC,vD),fk3_taprsfki(fk1_funct_1(vB,vD))))) -> (pEq(vC,fk2_pmboolean(vA,vB))))))))
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( ( ~pEq(vC,fcfk1_xboole_0(cvEMPTY)) -> pEq(fk4_closupre2(vA,vB,vC),fk3_closupre2(vC)) ) and ( pEq(vC,fcfk1_xboole_0(cvEMPTY)) -> pEq(fk4_closupre2(vA,vB,vC),fk1_pboole(vA)) ) ) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> @ vD .  ( pm4_pboole(vD,vA,vB) -> (((pEq(vD,fk2_closupre3(vA,vB,vC))) -> (@ vE .  ( pr2_hidden(vE,vA) -> pEq(fk1_funct_1(vD,vE),fk3_taprsfki(fa_4_0_closupre3(vA,vB,vC,vE))) ))) and ((@ vE .  ( pr2_hidden(vE,vA) -> pEq(fk1_funct_1(vD,vE),fk3_taprsfki(fa_4_0_closupre3(vA,vB,vC,vE))) )) -> (pEq(vD,fk2_closupre3(vA,vB,vC)))))) ) ) )
( @ vA . pEq(fk1_pboole(vA),fk2_funcop_1(vA,fcfk1_xboole_0(cvEMPTY))) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> pm1_pboole(fk1_pmboolean(vA,vB),vA) ) )
( @ vA . pm1_pboole(fk1_pboole(vA),vA) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> pm1_subset_1(fk2_closupre2(vA,vB),fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> pm4_pboole(fk2_closupre3(vA,vB,vC),vA,vB) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> pm1_pboole(fk2_pmboolean(vA,vB),vA) ) )
( @ vA .  ( pv1_fpraenfkel(vA) -> ( pv1_prelat_1(fk3_closupre2(vA)) and pv1_funct_1(fk3_closupre2(vA)) ) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> pm1_pboole(fk4_closupre2(vA,vB,vC),vA) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> pm4_pboole(fk5_closupre2(vA,vB,vC),vA,fk1_pmboolean(vA,vB)) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ( pv1_closupre2(fk6_closupre2(vA,vB),vA,vB) and pv2_closupre2(fk6_closupre2(vA,vB),vA,vB) and pv3_closupre2(fk6_closupre2(vA,vB),vA,vB) and pv4_closupre2(fk6_closupre2(vA,vB),vA,vB) and pv5_closupre2(fk6_closupre2(vA,vB),vA,vB) and pv6_closupre2(fk6_closupre2(vA,vB),vA,vB) and pm1_subset_1(fk6_closupre2(vA,vB),fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> @ vD .  ( pm1_closupre2(vD,vA,vB,vC) -> pm4_pboole(vD,vA,vB) ) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> @ vD .  ( pm1_closupre3(vD,vA,vB,vC) -> pm1_pboole(vD,vA) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ( pv1_prelat_1(vB) and pv1_funct_1(vB) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm4_pboole(vC,vA,vB) -> pm1_pboole(vC,vA) ) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> ? vD . pm1_closupre2(vD,vA,vB,vC) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> ? vD . pm1_closupre3(vD,vA,vB,vC) ) )
( @ vA .  ? vB . pm1_pboole(vB,vA) )
( @ vA .  ? vB . pm1_subset_1(vB,vA) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC . pm4_pboole(vC,vA,vB) ) )
( @ vA .  ( pv1_prelat_1(fk1_pboole(vA)) and pv3_prelat_1(fk1_pboole(vA)) and pv1_funct_1(fk1_pboole(vA)) and pv1_ppre_ciprc(fk1_pboole(vA),vA) ) )
( @ vA . ~ pv1_xboole_0(fk1_zfpmisc_1(vA)) )
( pv1_xboole_0(fcfk1_xboole_0(cvEMPTY)) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ( ~ pv1_xboole_0(fk1_closupre2(vA,vB)) and pv1_fpraenfkel(fk1_closupre2(vA,vB)) and pv1_ppralg_2(fk1_closupre2(vA,vB)) ) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> ( pv1_prelat_1(fk2_closupre3(vA,vB,vC)) and pv3_prelat_1(fk2_closupre3(vA,vB,vC)) and pv1_funct_1(fk2_closupre3(vA,vB,vC)) and pv1_ppre_ciprc(fk2_closupre3(vA,vB,vC),vA) ) ) )
( @ vA . @ vB . @ vC .  ( ( ~ pv1_xboole_0(vA) and pv2_prelat_1(vB) and pm1_pboole(vB,vA) and pm1_subset_1(vC,vA) ) -> ~ pv1_xboole_0(fk1_funct_1(vB,vC)) ) )
( @ vA .  ( ( pv1_xboole_0(vA) and pv1_fpraenfkel(vA) ) -> ( pv1_xboole_0(fk3_closupre2(vA)) and pv1_prelat_1(fk3_closupre2(vA)) and pv1_funct_1(fk3_closupre2(vA)) and pv2_funct_1(fk3_closupre2(vA)) and pv1_finset_1(fk3_closupre2(vA)) and pv1_fpraenfkel(fk3_closupre2(vA)) ) ) )
( @ vA .  ( pv1_prelat_1(fk1_pboole(vA)) and pv3_prelat_1(fk1_pboole(vA)) and pv1_funct_1(fk1_pboole(vA)) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> ( pv1_prelat_1(fk4_closupre2(vA,vB,vC)) and pv3_prelat_1(fk4_closupre2(vA,vB,vC)) and pv1_funct_1(fk4_closupre2(vA,vB,vC)) and pv1_ppre_ciprc(fk4_closupre2(vA,vB,vC),vA) ) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> ( pv1_prelat_1(fk4_closupre2(vA,vB,vC)) and pv2_prelat_1(fk4_closupre2(vA,vB,vC)) and pv1_funct_1(fk4_closupre2(vA,vB,vC)) ) ) )
( @ vA . @ vB .  ( ( pv1_ppre_ciprc(vB,vA) and pm1_pboole(vB,vA) ) -> ( pv1_prelat_1(fk1_pmboolean(vA,vB)) and pv2_prelat_1(fk1_pmboolean(vA,vB)) and pv1_funct_1(fk1_pmboolean(vA,vB)) and pv1_ppre_ciprc(fk1_pmboolean(vA,vB),vA) ) ) )
( @ vA . @ vB . @ vC . @ vD . @ vE .  ( ( pm1_pboole(vC,vB) and pm1_subset_1(vD,fk1_zfpmisc_1(fk1_closupre2(vB,vC))) ) -> (((pr2_hidden(vA,fa_4_0_closupre2(vB,vC,vD,vE))) -> (? vF .  ( pm1_closupre2(vF,vB,vC,fk2_closupre2(vB,vC)) and pEq(vA,fk1_funct_1(vF,vE)) and pr2_hidden(vF,vD) ))) and ((? vF .  ( pm1_closupre2(vF,vB,vC,fk2_closupre2(vB,vC)) and pEq(vA,fk1_funct_1(vF,vE)) and pr2_hidden(vF,vD) )) -> (pr2_hidden(vA,fa_4_0_closupre2(vB,vC,vD,vE)))))) )
( @ vA . @ vB . @ vC . @ vD . @ vE .  ( ( pm1_pboole(vC,vB) and pm1_subset_1(vD,fk1_zfpmisc_1(fk1_closupre2(vB,vC))) ) -> (((pr2_hidden(vA,fa_4_0_closupre3(vB,vC,vD,vE))) -> (? vF .  ( pm1_closupre2(vF,vB,vC,fk6_closupre2(vB,vC)) and pEq(vA,fk1_funct_1(vF,vE)) and pr2_hidden(vF,vD) ))) and ((? vF .  ( pm1_closupre2(vF,vB,vC,fk6_closupre2(vB,vC)) and pEq(vA,fk1_funct_1(vF,vE)) and pr2_hidden(vF,vD) )) -> (pr2_hidden(vA,fa_4_0_closupre3(vB,vC,vD,vE)))))) )
( @ vA . @ vB . @ vC . @ vD . @ vE .  ( ( pm1_pboole(vC,vB) and pm1_subset_1(vD,fk1_zfpmisc_1(fk1_closupre2(vB,vC))) ) -> (((pr2_hidden(vA,fa_4_4_closupre3(vB,vC,vD,vE))) -> (? vF .  ( pm1_closupre3(vF,vB,vC,fk6_closupre2(vB,vC)) and pEq(vA,fk1_funct_1(vF,vE)) and pr2_hidden(vF,vD) ))) and ((? vF .  ( pm1_closupre3(vF,vB,vC,fk6_closupre2(vB,vC)) and pEq(vA,fk1_funct_1(vF,vE)) and pr2_hidden(vF,vD) )) -> (pr2_hidden(vA,fa_4_4_closupre3(vB,vC,vD,vE)))))) )
( ? vA .  ( pv1_xboole_0(vA) and pv1_prelat_1(vA) and pv1_funct_1(vA) and pv2_funct_1(vA) and pv1_finset_1(vA) and pv1_fpraenfkel(vA) ) )
( ? vA .  ( ~ pv1_xboole_0(vA) and pv1_finset_1(vA) ) )
( ? vA .  ( pv1_prelat_1(vA) and pv1_funct_1(vA) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC .  ( pm4_pboole(vC,vA,vB) and pv1_prelat_1(vC) and pv3_prelat_1(vC) and pv1_funct_1(vC) and pv1_ppre_ciprc(vC,vA) ) ) )
( ? vA .  ( pv1_prelat_1(vA) and pv3_prelat_1(vA) and pv1_funct_1(vA) ) )
( @ vA .  ( ~ pv1_xboole_0(vA) -> ? vB .  ( pm1_subset_1(vB,fk1_zfpmisc_1(vA)) and ~ pv1_xboole_0(vB) ) ) )
( ? vA . pv1_xboole_0(vA) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) and ~ pv1_xboole_0(vC) and pv1_fpraenfkel(vC) and pv1_ppralg_2(vC) ) ) )
( ? vA .  ( pv1_prelat_1(vA) and pv1_xboole_0(vA) and pv1_funct_1(vA) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC .  ( pm4_pboole(vC,vA,fk1_pmboolean(vA,vB)) and pv1_prelat_1(vC) and pv2_prelat_1(vC) and pv1_funct_1(vC) ) ) )
( @ vA .  ? vB .  ( pm1_pboole(vB,vA) and pv1_prelat_1(vB) and pv3_prelat_1(vB) and pv1_funct_1(vB) ) )
( @ vA .  ? vB .  ( pm1_subset_1(vB,fk1_zfpmisc_1(vA)) and pv1_xboole_0(vB) ) )
( ? vA . ~ pv1_xboole_0(vA) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) and pv1_xboole_0(vC) and pv1_prelat_1(vC) and pv1_funct_1(vC) and pv2_funct_1(vC) and pv1_finset_1(vC) and pv1_fpraenfkel(vC) ) ) )
( @ vA .  ( ~ pv1_xboole_0(vA) -> ? vB .  ( pm1_subset_1(vB,fk1_zfpmisc_1(vA)) and ~ pv1_xboole_0(vB) and pv1_finset_1(vB) ) ) )
( ? vA .  ( pv1_prelat_1(vA) and pv1_funct_1(vA) and pv2_funct_1(vA) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC .  ( pm4_pboole(vC,vA,fk1_pmboolean(vA,vB)) and pv1_prelat_1(vC) and pv3_prelat_1(vC) and pv1_funct_1(vC) and pv1_ppre_ciprc(vC,vA) ) ) )
( @ vA .  ? vB .  ( pm1_pboole(vB,vA) and pv1_prelat_1(vB) and pv2_prelat_1(vB) and pv1_funct_1(vB) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> ? vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) and ~ pv1_xboole_0(vC) and pv1_fpraenfkel(vC) and pv1_ppralg_2(vC) and pv1_closupre2(vC,vA,vB) and pv2_closupre2(vC,vA,vB) and pv3_closupre2(vC,vA,vB) and pv4_closupre2(vC,vA,vB) and pv5_closupre2(vC,vA,vB) and pv6_closupre2(vC,vA,vB) ) ) )
( @ vA .  ( ~ pv1_xboole_0(vA) -> ? vB .  ( pm1_subset_1(vB,fk1_zfpmisc_1(vA)) and ~ pv1_xboole_0(vB) and pv1_finset_1(vB) ) ) )
( ? vA .  ( pv1_prelat_1(vA) and pv3_prelat_1(vA) and pv1_funct_1(vA) ) )
( @ vA . @ vB .  ( ( pv1_ppre_ciprc(vB,vA) and pm1_pboole(vB,vA) ) -> ? vC .  ( pm4_pboole(vC,vA,fk1_pmboolean(vA,vB)) and pv1_prelat_1(vC) and pv2_prelat_1(vC) and pv1_funct_1(vC) and pv1_ppre_ciprc(vC,vA) ) ) )
( ? vA .  ( pv1_prelat_1(vA) and pv2_prelat_1(vA) and pv1_funct_1(vA) ) )
( @ vA . @ vB .  ( ( pv2_prelat_1(vB) and pm1_pboole(vB,vA) ) -> ? vC .  ( pm4_pboole(vC,vA,vB) and pv1_prelat_1(vC) and pv2_prelat_1(vC) and pv1_funct_1(vC) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> pEq(fk2_closupre2(vA,vB),fk1_closupre2(vA,vB)) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> pEq(fk5_closupre2(vA,vB,vC),fk4_closupre2(vA,vB,vC)) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> pEq(fk6_closupre2(vA,vB),fk1_closupre2(vA,vB)) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> @ vD .  (((pm1_closupre2(vD,vA,vB,vC)) -> (pm1_subset_1(vD,vC))) and ((pm1_subset_1(vD,vC)) -> (pm1_closupre2(vD,vA,vB,vC))))) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and ~ pv1_xboole_0(vC) and pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) ) -> @ vD .  (((pm1_closupre3(vD,vA,vB,vC)) -> (pm1_subset_1(vD,vC))) and ((pm1_subset_1(vD,vC)) -> (pm1_closupre3(vD,vA,vB,vC))))) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_pboole(vC,vA) ) -> (((pr6_pboole(vA,vB,vC)) -> (pEq(vB,vC))) and ((pEq(vB,vC)) -> (pr6_pboole(vA,vB,vC))))) )
( @ vA . @ vB . pr1_taprsfki(vA,vA) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_pboole(vC,vA) ) -> pr6_pboole(vA,vB,vB) ) )
( @ vA . @ vB . @ vC .  ( ( pm1_pboole(vB,vA) and pm1_pboole(vC,vA) ) -> ( pr6_pboole(vA,vB,vC) -> pr6_pboole(vA,vC,vB) ) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> ( ~ pv1_xboole_0(vC) -> @ vD .  ( pr2_hidden(vD,vA) -> pEq(fk1_funct_1(fk4_closupre2(vA,vB,vC),vD),fa_4_0_closupre2(vA,vB,vC,vD)) ) ) ) ) )
( @ vA . @ vB .  ( pr2_hidden(vA,vB) -> pm1_subset_1(vA,vB) ) )
( @ vA . pr6_pboole(vA,fk2_pmboolean(vA,fk1_pboole(vA)),fk1_pboole(vA)) )
( @ vA . @ vB .  ( pm1_subset_1(vA,vB) -> ( pv1_xboole_0(vB) or pr2_hidden(vA,vB) ) ) )
( @ vA . @ vB .  ( @ vC .  (((pr2_hidden(vC,vA)) -> (pr2_hidden(vC,vB))) and ((pr2_hidden(vC,vB)) -> (pr2_hidden(vC,vA)))) -> pEq(vA,vB) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_pboole(vC,vA) -> ( @ vD .  ( pr2_hidden(vD,vA) -> pEq(fk1_funct_1(vB,vD),fk1_funct_1(vC,vD)) ) -> pEq(vB,vC) ) ) ) )
( @ vA . @ vB .  (((pm1_subset_1(vA,fk1_zfpmisc_1(vB))) -> (pr1_taprsfki(vA,vB))) and ((pr1_taprsfki(vA,vB)) -> (pm1_subset_1(vA,fk1_zfpmisc_1(vB))))))
( @ vA . @ vB . @ vC .  ( ( pr2_hidden(vA,vB) and pm1_subset_1(vB,fk1_zfpmisc_1(vC)) ) -> pm1_subset_1(vA,vC) ) )
( @ vA . @ vB . @ vC .  ~ ( pr2_hidden(vA,vB) and pm1_subset_1(vB,fk1_zfpmisc_1(vC)) and pv1_xboole_0(vC) ) )
( @ vA .  ( pv1_xboole_0(vA) -> pEq(vA,fcfk1_xboole_0(cvEMPTY)) ) )
( @ vA . @ vB .  ~ ( pr2_hidden(vA,vB) and pv1_xboole_0(vB) ) )
( @ vA . @ vB .  ~ ( pv1_xboole_0(vA) and ~pEq(vA,vB) and pv1_xboole_0(vB) ) )
( @ vA . @ vB .  ( pm1_pboole(vB,vA) -> @ vC .  ( pm1_subset_1(vC,fk1_zfpmisc_1(fk1_closupre2(vA,vB))) -> pr6_pboole(vA,fk2_closupre3(vA,vB,vC),fk2_pmboolean(vA,fk5_closupre2(vA,vB,vC))) ) ) )
