8
@ vA . @ vB . ( ( pEq(vvA, vB) and pcd(vvA) ) -> pcd(vB) )
@ vA . @ vB . ( ( pEq(vvA, vB) and pcowlNothing(vvA) ) -> pcowlNothing(vB) )
@ vA . @ vB . ( ( pEq(vvA, vB )and pcowlThing(vvA) ) -> pcowlThing(vB) )
@ vA . @ vB . @ vC . ( ( pEq(vvA, vB) and prp(vvA,vC) ) -> prp(vB,vC) )
@ vA . @ vB . @ vC . ( ( pEq(vvA, vB) and prp(vC,vvA) ) -> prp(vC,vB) )
@ vA . @ vB . @ vC . ( ( pEq(vvA, vB) and prq(vvA,vC) ) -> prq(vB,vC) )
@ vA . @ vB . @ vC . ( ( pEq(vvA, vB) and prq(vC,vvA) ) -> prq(vC,vB) )
@ vA . @ vB . ( ( pEq(vvA, vB) and pxsd_integer(vvA) ) -> pxsd_integer(vB) )
@ vA . @ vB . ( ( pEq(vvA, vB) and pxsd_string(vvA) ) -> pxsd_string(vB) )
@ vX . ( pcowlThing(vX) and ~ pcowlNothing(vX) )
@ vX . ( (pxsd_string(vX) -> ~ pxsd_integer(vX)) and (~ pxsd_integer(vX) -> pxsd_string(vX)) )
@ vX . ( pcd(vX) <-> prq(vX,iv) )
@ vX . ((pcd(vX) -> prp(vX,iv)) and (prp(vX,iv) -> pcd(vX)))
@ vX . @ vY . @ vZ . ( ( prp(vX,vY) and prp(vX,vZ) ) -> vY = vZ )
@ vX . @ vY . ( prp(vX,vY) -> pcd(vX) )
@ vX . @ vY . @ vZ . ( ( prq(vX,vY) and prq(vX,vZ) ) -> vY = vZ )
@ vX . @ vY . ( prq(vX,vY) -> pcd(vX) )
pcowlThing(civ)
( @ vX . ( pcowlThing(vX) and ~ pcowlNothing(vX) ) and @ vX . ( (pxsd_string(vX) -> ~ pxsd_integer(vX)) and (~ pxsd_integer(vX) -> pxsd_string(vX)) ) and @ vX . @ vY . ( (pprq(vX,vY) -> prp(vX,vY)) and (prp(vX,vY) -> prq(vX,vY)) ) )
